services:
  ojs.twig.display_extension:
    class: EP\DisplayBundle\Service\Twig\DisplayExtension
    arguments:
      - "@translator"
      - "@annotation_reader"
      - "@twig"
    tags:
      - { name: twig.extension }